///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RonwellTask
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CASE3 recording.
    /// </summary>
    [TestModule("530edb37-a66e-44d0-ac07-ece67b5840ee", ModuleType.Recording, 1)]
    public partial class CASE3 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RonwellTaskRepository repository.
        /// </summary>
        public static RonwellTaskRepository repo = RonwellTaskRepository.Instance;

        static CASE3 instance = new CASE3();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CASE3()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CASE3 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping' at 37;9.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.GroupingInfo, new RecordItemIndex(0));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping.Click("37;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOl' at 110;25.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOlInfo, new RecordItemIndex(1));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOl.Click("110;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.ComboBox' at 187;25.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.ComboBoxInfo, new RecordItemIndex(2));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.ComboBox.Click("187;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '     ' with focus on 'HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.ComboBox'.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.ComboBoxInfo, new RecordItemIndex(3));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.ComboBox.PressKeys("     ");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.Text' at 121;19.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.TextInfo, new RecordItemIndex(4));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.Text.Click("121;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '       ' with focus on 'HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.Text'.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.TextInfo, new RecordItemIndex(5));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.Text.PressKeys("       ");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.UEYEOL' at 218;15.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.UEYEOLInfo, new RecordItemIndex(6));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.UEYEOL.Click("218;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.Grouping'.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.GroupingInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.GroupingInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
