///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RonwellTask
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CASE4 recording.
    /// </summary>
    [TestModule("61557e7d-5dd0-445d-a19e-19e36a830bea", ModuleType.Recording, 1)]
    public partial class CASE4 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RonwellTaskRepository repository.
        /// </summary>
        public static RonwellTaskRepository repo = RonwellTaskRepository.Instance;

        static CASE4 instance = new CASE4();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CASE4()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CASE4 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpsCdnDsmcdnComMnresize200200' at 45;43.", repo.ApplicationUnderTest.HttpsCdnDsmcdnComMnresize200200Info, new RecordItemIndex(0));
            repo.ApplicationUnderTest.HttpsCdnDsmcdnComMnresize200200.Click("45;43");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 467;339.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Self.Click("467;339");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SepeteEkle' at 144;14.", repo.ApplicationUnderTest.SepeteEkleInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.SepeteEkle.Click("144;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.Back' at 19;15.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.BackInfo, new RecordItemIndex(3));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.Back.Click("19;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpsCdnDsmcdnComTy335ProductMe' at 133;211.", repo.ApplicationUnderTest.HttpsCdnDsmcdnComTy335ProductMeInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.HttpsCdnDsmcdnComTy335ProductMe.Click("133;211");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 988;588.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Self.Click("988;588");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Sepetim' at 32;12.", repo.ApplicationUnderTest.SepetimInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Sepetim.Click("32;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ApplicationUnderTest.PbWrapper1.PbWrapper'.", repo.ApplicationUnderTest.PbWrapper1.PbWrapperInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ApplicationUnderTest.PbWrapper1.PbWrapperInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Valid='True') on item 'ApplicationUnderTest.PbWrapper1.PbWrapper'.", repo.ApplicationUnderTest.PbWrapper1.PbWrapperInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.ApplicationUnderTest.PbWrapper1.PbWrapperInfo, "Valid", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.PbWrapper1.PbWrapper'.", repo.ApplicationUnderTest.PbWrapper1.PbWrapperInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.ApplicationUnderTest.PbWrapper1.PbWrapperInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ApplicationUnderTest.PbWrapper1.PbBasketItem'.", repo.ApplicationUnderTest.PbWrapper1.PbBasketItemInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.ApplicationUnderTest.PbWrapper1.PbBasketItemInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Valid='True') on item 'ApplicationUnderTest.PbWrapper1.PbBasketItem'.", repo.ApplicationUnderTest.PbWrapper1.PbBasketItemInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.ApplicationUnderTest.PbWrapper1.PbBasketItemInfo, "Valid", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.PbWrapper1.PbBasketItem'.", repo.ApplicationUnderTest.PbWrapper1.PbBasketItemInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.ApplicationUnderTest.PbWrapper1.PbBasketItemInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ApplicationUnderTest.PbWrapper1.PbBasketItem1'.", repo.ApplicationUnderTest.PbWrapper1.PbBasketItem1Info, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.ApplicationUnderTest.PbWrapper1.PbBasketItem1Info, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Valid='True') on item 'ApplicationUnderTest.PbWrapper1.PbBasketItem1'.", repo.ApplicationUnderTest.PbWrapper1.PbBasketItem1Info, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.ApplicationUnderTest.PbWrapper1.PbBasketItem1Info, "Valid", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ApplicationUnderTest.PbWrapper1.PbBasketItem1'.", repo.ApplicationUnderTest.PbWrapper1.PbBasketItem1Info, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.ApplicationUnderTest.PbWrapper1.PbBasketItem1Info, "Visible", "True");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
