///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RonwellTask
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CASE7 recording.
    /// </summary>
    [TestModule("148b254f-6b88-44f8-99bd-1c1693adc8c5", ModuleType.Recording, 1)]
    public partial class CASE7 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RonwellTaskRepository repository.
        /// </summary>
        public static RonwellTaskRepository repo = RonwellTaskRepository.Instance;

        static CASE7 instance = new CASE7();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CASE7()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CASE7 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping1'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping1Info, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping1Info, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Valid='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping1'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping1Info, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping1Info, "Valid", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping1'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping1Info, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping1Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping2' at 1221;247.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping2Info, new RecordItemIndex(3));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping2.Click("1221;247");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping1'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping1Info, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping1Info, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Valid='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping1'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping1Info, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping1Info, "Valid", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping1'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping1Info, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping1Info, "Visible", "True");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
