///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RonwellTask
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RonwellTaskRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f5d16358-5511-42a0-8239-c75465ed1e0e")]
    public partial class RonwellTaskRepository : RepoGenBaseFolder
    {
        static RonwellTaskRepository instance = new RonwellTaskRepository();
        RonwellTaskRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        RonwellTaskRepositoryFolders.NewIncognitoTabGoogleChromeAppFolder _newincognitotabgooglechrome;
        RonwellTaskRepositoryFolders.KadınButikleriYeniSezonUEruenleriAppFolder _kadınbutikleriyenisezonueruenleri;
        RonwellTaskRepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder _entrendueruenlertuerkiyeninonlineal;
        RonwellTaskRepositoryFolders.HttpsWwwTrendyolComUyelikcbEqhttpsAppFolder _httpswwwtrendyolcomuyelikcbeqhttps;
        RonwellTaskRepositoryFolders.ErkekButikleriYeniSezonUEruenlerAppFolder _erkekbutikleriyenisezonueruenler;
        RepoItemInfo _girişyapInfo;

        /// <summary>
        /// Gets the singleton class instance representing the RonwellTaskRepository element repository.
        /// </summary>
        [RepositoryFolder("f5d16358-5511-42a0-8239-c75465ed1e0e")]
        public static RonwellTaskRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RonwellTaskRepository() 
            : base("RonwellTaskRepository", "/", null, 0, false, "f5d16358-5511-42a0-8239-c75465ed1e0e", ".\\RepositoryImages\\RonwellTaskRepositoryf5d16358.rximgres")
        {
            _applicationundertest = new RonwellTaskRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _newincognitotabgooglechrome = new RonwellTaskRepositoryFolders.NewIncognitoTabGoogleChromeAppFolder(this);
            _kadınbutikleriyenisezonueruenleri = new RonwellTaskRepositoryFolders.KadınButikleriYeniSezonUEruenleriAppFolder(this);
            _entrendueruenlertuerkiyeninonlineal = new RonwellTaskRepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder(this);
            _httpswwwtrendyolcomuyelikcbeqhttps = new RonwellTaskRepositoryFolders.HttpsWwwTrendyolComUyelikcbEqhttpsAppFolder(this);
            _erkekbutikleriyenisezonueruenler = new RonwellTaskRepositoryFolders.ErkekButikleriYeniSezonUEruenlerAppFolder(this);
            _girişyapInfo = new RepoItemInfo(this, "GirişYap", "/form[@title>'https://www.trendyol.com/']/element[@automationid='305295744']/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[1]/container[1]/container/container[@accessiblerole='Grouping']/container[2]/container/container[1]//text[@accessiblename='Giriş Yap']", 30000, null, "8fab4b6a-3ae6-44d7-abe3-ce14a85fac25");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f5d16358-5511-42a0-8239-c75465ed1e0e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The GirişYap item.
        /// </summary>
        [RepositoryItem("8fab4b6a-3ae6-44d7-abe3-ce14a85fac25")]
        public virtual Ranorex.Text GirişYap
        {
            get
            {
                 return _girişyapInfo.CreateAdapter<Ranorex.Text>(true);
            }
        }

        /// <summary>
        /// The GirişYap item info.
        /// </summary>
        [RepositoryItemInfo("8fab4b6a-3ae6-44d7-abe3-ce14a85fac25")]
        public virtual RepoItemInfo GirişYapInfo
        {
            get
            {
                return _girişyapInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("4b5a4ea3-6f8d-4143-921a-c240c672192e")]
        public virtual RonwellTaskRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The NewIncognitoTabGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("7d074ade-a53c-4d63-a0ae-4a6a2e9de501")]
        public virtual RonwellTaskRepositoryFolders.NewIncognitoTabGoogleChromeAppFolder NewIncognitoTabGoogleChrome
        {
            get { return _newincognitotabgooglechrome; }
        }

        /// <summary>
        /// The KadınButikleriYeniSezonUEruenleri folder.
        /// </summary>
        [RepositoryFolder("6efdd5f2-e3f9-4a05-8fbc-8e5e324b6692")]
        public virtual RonwellTaskRepositoryFolders.KadınButikleriYeniSezonUEruenleriAppFolder KadınButikleriYeniSezonUEruenleri
        {
            get { return _kadınbutikleriyenisezonueruenleri; }
        }

        /// <summary>
        /// The EnTrendUEruenlerTuerkiyeninOnlineAl folder.
        /// </summary>
        [RepositoryFolder("59902057-57e5-4852-9d90-3c428cc4bb45")]
        public virtual RonwellTaskRepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder EnTrendUEruenlerTuerkiyeninOnlineAl
        {
            get { return _entrendueruenlertuerkiyeninonlineal; }
        }

        /// <summary>
        /// The HttpsWwwTrendyolComUyelikcbEqhttps folder.
        /// </summary>
        [RepositoryFolder("ed9dd564-d49e-46a2-96ac-41322745723e")]
        public virtual RonwellTaskRepositoryFolders.HttpsWwwTrendyolComUyelikcbEqhttpsAppFolder HttpsWwwTrendyolComUyelikcbEqhttps
        {
            get { return _httpswwwtrendyolcomuyelikcbeqhttps; }
        }

        /// <summary>
        /// The ErkekButikleriYeniSezonUEruenler folder.
        /// </summary>
        [RepositoryFolder("1171294e-7dde-4fa0-975e-c625dc7ac3a4")]
        public virtual RonwellTaskRepositoryFolders.ErkekButikleriYeniSezonUEruenlerAppFolder ErkekButikleriYeniSezonUEruenler
        {
            get { return _erkekbutikleriyenisezonueruenler; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RonwellTaskRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("4b5a4ea3-6f8d-4143-921a-c240c672192e")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RonwellTaskRepositoryFolders.LoginRegisterFolder _loginregister;
            RonwellTaskRepositoryFolders.PbWrapper1Folder _pbwrapper1;
            RepoItemInfo _loginemailInfo;
            RepoItemInfo _loginpasswordinputInfo;
            RepoItemInfo _containerInfo;
            RepoItemInfo _httpscdndsmcdncommnresize200200Info;
            RepoItemInfo _sepeteekleInfo;
            RepoItemInfo _httpscdndsmcdncomty335productmeInfo;
            RepoItemInfo _sepetimInfo;
            RepoItemInfo _someimgtagInfo;
            RepoItemInfo _accountuserlinkInfo;
            RepoItemInfo _ueyeolInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.trendyol.com']", parentFolder, 30000, null, false, "4b5a4ea3-6f8d-4143-921a-c240c672192e", "")
            {
                _loginregister = new RonwellTaskRepositoryFolders.LoginRegisterFolder(this);
                _pbwrapper1 = new RonwellTaskRepositoryFolders.PbWrapper1Folder(this);
                _loginemailInfo = new RepoItemInfo(this, "LoginEmail", ".//input[#'login-email']", ".//input[#'login-email']", 30000, null, "194f6640-d002-4bde-ba51-95a0ec42ccf1");
                _loginpasswordinputInfo = new RepoItemInfo(this, "LoginPasswordInput", ".//input[#'login-password-input']", ".//input[#'login-password-input']", 30000, null, "02f19a24-5ac6-4561-b5cd-9709a4a683cb");
                _containerInfo = new RepoItemInfo(this, "Container", ".//div[#'container']", ".//div[#'container']", 30000, null, "912f56e3-7f2a-49bd-9386-875ece78ba8c");
                _httpscdndsmcdncommnresize200200Info = new RepoItemInfo(this, "HttpsCdnDsmcdnComMnresize200200", ".//div[#'browsing-gw-homepage']/div/div/div/article[1]/div/div/div[2]/a[1]/img[@src='https://cdn.dsmcdn.com/mnresize/200/200/marketing/datascience/automation/2022/3/9/Top_Widget_202203091801.png']", ".//div[#'browsing-gw-homepage']//img[@src='https://cdn.dsmcdn.com/mnresize/200/200/marketing/datascience/automation/2022/3/9/Top_Widget_202203091801.png']", 30000, null, "7d7f66b4-4955-4c84-aa96-a0d94573397c");
                _sepeteekleInfo = new RepoItemInfo(this, "SepeteEkle", ".//main[#'product-detail-app']/div/div[2]/div[1]/div[2]/div[2]/div[7]/button/div[@innertext='Sepete Ekle']", ".//main[#'product-detail-app']//div[@innertext='Sepete Ekle']", 30000, null, "ecfcf7ce-b259-48e2-9f7b-0172620a2fdf");
                _httpscdndsmcdncomty335productmeInfo = new RepoItemInfo(this, "HttpsCdnDsmcdnComTy335ProductMe", ".//div[#'account-gw-just-for-you']/div/div/div/div[2]/a[@href>'https://www.trendyol.com/']/img[@src='https://cdn.dsmcdn.com//ty335/product/media/images/20220218/13/53030145/116829745/1/1_org.jpg']", ".//div[#'account-gw-just-for-you']//img[@src='https://cdn.dsmcdn.com//ty335/product/media/images/20220218/13/53030145/116829745/1/1_org.jpg']", 30000, null, "feb0d9ca-79b1-447f-ba84-62c1b6aafbd3");
                _sepetimInfo = new RepoItemInfo(this, "Sepetim", ".//div[#'account-navigation-container']/div/div[2]/a[@href>'https://www.trendyol.com/']/p[@innertext='Sepetim']", ".//div[#'account-navigation-container']//p[@innertext='Sepetim']", 30000, null, "7c4d1e9f-539a-493b-a953-54c272c8f1d2");
                _someimgtagInfo = new RepoItemInfo(this, "SomeImgTag", "body/div/div/div//img", "body/div/div/div/div/div/div/div/a/img", 30000, null, "733c9ca7-9f90-46ff-9afc-8a4c769b27c8");
                _accountuserlinkInfo = new RepoItemInfo(this, "AccountUserLink", ".//div[#'account-navigation-container']/div/div[1]/div[1]", ".//div[#'account-navigation-container']/div/div[1]/div[1]", 30000, null, "b749ad8b-16a0-47b2-989f-53c6cecb72c5");
                _ueyeolInfo = new RepoItemInfo(this, "UEyeOl", ".//div[#'account-navigation-container']/div/div[1]//div[@innertext='Üye Ol']", ".//div[#'account-navigation-container']//div[@innertext='Üye Ol']", 30000, null, "bb34690f-5476-4814-9142-dc8b6358cb8b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4b5a4ea3-6f8d-4143-921a-c240c672192e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4b5a4ea3-6f8d-4143-921a-c240c672192e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginEmail item.
            /// </summary>
            [RepositoryItem("194f6640-d002-4bde-ba51-95a0ec42ccf1")]
            public virtual Ranorex.InputTag LoginEmail
            {
                get
                {
                    return _loginemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginEmail item info.
            /// </summary>
            [RepositoryItemInfo("194f6640-d002-4bde-ba51-95a0ec42ccf1")]
            public virtual RepoItemInfo LoginEmailInfo
            {
                get
                {
                    return _loginemailInfo;
                }
            }

            /// <summary>
            /// The LoginPasswordInput item.
            /// </summary>
            [RepositoryItem("02f19a24-5ac6-4561-b5cd-9709a4a683cb")]
            public virtual Ranorex.InputTag LoginPasswordInput
            {
                get
                {
                    return _loginpasswordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginPasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("02f19a24-5ac6-4561-b5cd-9709a4a683cb")]
            public virtual RepoItemInfo LoginPasswordInputInfo
            {
                get
                {
                    return _loginpasswordinputInfo;
                }
            }

            /// <summary>
            /// The Container item.
            /// </summary>
            [RepositoryItem("912f56e3-7f2a-49bd-9386-875ece78ba8c")]
            public virtual Ranorex.DivTag Container
            {
                get
                {
                    return _containerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Container item info.
            /// </summary>
            [RepositoryItemInfo("912f56e3-7f2a-49bd-9386-875ece78ba8c")]
            public virtual RepoItemInfo ContainerInfo
            {
                get
                {
                    return _containerInfo;
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComMnresize200200 item.
            /// </summary>
            [RepositoryItem("7d7f66b4-4955-4c84-aa96-a0d94573397c")]
            public virtual Ranorex.ImgTag HttpsCdnDsmcdnComMnresize200200
            {
                get
                {
                    return _httpscdndsmcdncommnresize200200Info.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComMnresize200200 item info.
            /// </summary>
            [RepositoryItemInfo("7d7f66b4-4955-4c84-aa96-a0d94573397c")]
            public virtual RepoItemInfo HttpsCdnDsmcdnComMnresize200200Info
            {
                get
                {
                    return _httpscdndsmcdncommnresize200200Info;
                }
            }

            /// <summary>
            /// The SepeteEkle item.
            /// </summary>
            [RepositoryItem("ecfcf7ce-b259-48e2-9f7b-0172620a2fdf")]
            public virtual Ranorex.DivTag SepeteEkle
            {
                get
                {
                    return _sepeteekleInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SepeteEkle item info.
            /// </summary>
            [RepositoryItemInfo("ecfcf7ce-b259-48e2-9f7b-0172620a2fdf")]
            public virtual RepoItemInfo SepeteEkleInfo
            {
                get
                {
                    return _sepeteekleInfo;
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComTy335ProductMe item.
            /// </summary>
            [RepositoryItem("feb0d9ca-79b1-447f-ba84-62c1b6aafbd3")]
            public virtual Ranorex.ImgTag HttpsCdnDsmcdnComTy335ProductMe
            {
                get
                {
                    return _httpscdndsmcdncomty335productmeInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsCdnDsmcdnComTy335ProductMe item info.
            /// </summary>
            [RepositoryItemInfo("feb0d9ca-79b1-447f-ba84-62c1b6aafbd3")]
            public virtual RepoItemInfo HttpsCdnDsmcdnComTy335ProductMeInfo
            {
                get
                {
                    return _httpscdndsmcdncomty335productmeInfo;
                }
            }

            /// <summary>
            /// The Sepetim item.
            /// </summary>
            [RepositoryItem("7c4d1e9f-539a-493b-a953-54c272c8f1d2")]
            public virtual Ranorex.PTag Sepetim
            {
                get
                {
                    return _sepetimInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The Sepetim item info.
            /// </summary>
            [RepositoryItemInfo("7c4d1e9f-539a-493b-a953-54c272c8f1d2")]
            public virtual RepoItemInfo SepetimInfo
            {
                get
                {
                    return _sepetimInfo;
                }
            }

            /// <summary>
            /// The SomeImgTag item.
            /// </summary>
            [RepositoryItem("733c9ca7-9f90-46ff-9afc-8a4c769b27c8")]
            public virtual Ranorex.ImgTag SomeImgTag
            {
                get
                {
                    return _someimgtagInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The SomeImgTag item info.
            /// </summary>
            [RepositoryItemInfo("733c9ca7-9f90-46ff-9afc-8a4c769b27c8")]
            public virtual RepoItemInfo SomeImgTagInfo
            {
                get
                {
                    return _someimgtagInfo;
                }
            }

            /// <summary>
            /// The AccountUserLink item.
            /// </summary>
            [RepositoryItem("b749ad8b-16a0-47b2-989f-53c6cecb72c5")]
            public virtual Ranorex.DivTag AccountUserLink
            {
                get
                {
                    return _accountuserlinkInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The AccountUserLink item info.
            /// </summary>
            [RepositoryItemInfo("b749ad8b-16a0-47b2-989f-53c6cecb72c5")]
            public virtual RepoItemInfo AccountUserLinkInfo
            {
                get
                {
                    return _accountuserlinkInfo;
                }
            }

            /// <summary>
            /// The UEyeOl item.
            /// </summary>
            [RepositoryItem("bb34690f-5476-4814-9142-dc8b6358cb8b")]
            public virtual Ranorex.DivTag UEyeOl
            {
                get
                {
                    return _ueyeolInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The UEyeOl item info.
            /// </summary>
            [RepositoryItemInfo("bb34690f-5476-4814-9142-dc8b6358cb8b")]
            public virtual RepoItemInfo UEyeOlInfo
            {
                get
                {
                    return _ueyeolInfo;
                }
            }

            /// <summary>
            /// The LoginRegister folder.
            /// </summary>
            [RepositoryFolder("c09b1614-3e04-4fb1-9c9d-92d7db1f9f2b")]
            public virtual RonwellTaskRepositoryFolders.LoginRegisterFolder LoginRegister
            {
                get { return _loginregister; }
            }

            /// <summary>
            /// The PbWrapper1 folder.
            /// </summary>
            [RepositoryFolder("c8f40d99-e09b-4bc4-ae56-9d08a478505e")]
            public virtual RonwellTaskRepositoryFolders.PbWrapper1Folder PbWrapper1
            {
                get { return _pbwrapper1; }
            }
        }

        /// <summary>
        /// The LoginRegisterFolder folder.
        /// </summary>
        [RepositoryFolder("c09b1614-3e04-4fb1-9c9d-92d7db1f9f2b")]
        public partial class LoginRegisterFolder : RepoGenBaseFolder
        {
            RepoItemInfo _qbuttonqbuttonmediumqfluidqprimaInfo;
            RepoItemInfo _lrtitleInfo;
            RepoItemInfo _buttonqbuttonqbuttonmediumqsecondInfo;
            RepoItemInfo _lrcontainerInfo;
            RepoItemInfo _socialaccountloginbuttonsInfo;

            /// <summary>
            /// Creates a new LoginRegister  folder.
            /// </summary>
            public LoginRegisterFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginRegister", ".//div[#'login-register']", parentFolder, 30000, null, false, "c09b1614-3e04-4fb1-9c9d-92d7db1f9f2b", "")
            {
                _qbuttonqbuttonmediumqfluidqprimaInfo = new RepoItemInfo(this, "QButtonQButtonMediumQFluidQPrima", ".//form[@action='https://www.trendyol.com/giris?cb=https%3A%2F%2Fwww.trendyol.com%2F']/button", ".//form/button", 30000, null, "ebb0076f-8fc8-4517-8c22-aed06e632f1b");
                _lrtitleInfo = new RepoItemInfo(this, "LrTitle", "div[1]", "div[1]", 30000, null, "1a6c5cef-7f78-4712-ab73-e2085c675fad");
                _buttonqbuttonqbuttonmediumqsecondInfo = new RepoItemInfo(this, "ButtonQButtonQButtonMediumQSecond", "div[2]/div/button[2]", "div[2]/div/button[2]", 30000, null, "19cfa1e9-2610-459f-ba7f-b8fd78a7f459");
                _lrcontainerInfo = new RepoItemInfo(this, "LrContainer", "div[3]", "div[3]", 30000, null, "bbdee348-37f4-4fbb-a9a7-28dd89493408");
                _socialaccountloginbuttonsInfo = new RepoItemInfo(this, "SocialAccountLoginButtons", "div[3]/div[2]", "div[3]/div[2]", 30000, null, "8cf1c64a-c897-4d33-9615-0e1e028f6f49");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c09b1614-3e04-4fb1-9c9d-92d7db1f9f2b")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c09b1614-3e04-4fb1-9c9d-92d7db1f9f2b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima item.
            /// </summary>
            [RepositoryItem("ebb0076f-8fc8-4517-8c22-aed06e632f1b")]
            public virtual Ranorex.ButtonTag QButtonQButtonMediumQFluidQPrima
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprimaInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The QButtonQButtonMediumQFluidQPrima item info.
            /// </summary>
            [RepositoryItemInfo("ebb0076f-8fc8-4517-8c22-aed06e632f1b")]
            public virtual RepoItemInfo QButtonQButtonMediumQFluidQPrimaInfo
            {
                get
                {
                    return _qbuttonqbuttonmediumqfluidqprimaInfo;
                }
            }

            /// <summary>
            /// The LrTitle item.
            /// </summary>
            [RepositoryItem("1a6c5cef-7f78-4712-ab73-e2085c675fad")]
            public virtual Ranorex.DivTag LrTitle
            {
                get
                {
                    return _lrtitleInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The LrTitle item info.
            /// </summary>
            [RepositoryItemInfo("1a6c5cef-7f78-4712-ab73-e2085c675fad")]
            public virtual RepoItemInfo LrTitleInfo
            {
                get
                {
                    return _lrtitleInfo;
                }
            }

            /// <summary>
            /// The ButtonQButtonQButtonMediumQSecond item.
            /// </summary>
            [RepositoryItem("19cfa1e9-2610-459f-ba7f-b8fd78a7f459")]
            public virtual Ranorex.ButtonTag ButtonQButtonQButtonMediumQSecond
            {
                get
                {
                    return _buttonqbuttonqbuttonmediumqsecondInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ButtonQButtonQButtonMediumQSecond item info.
            /// </summary>
            [RepositoryItemInfo("19cfa1e9-2610-459f-ba7f-b8fd78a7f459")]
            public virtual RepoItemInfo ButtonQButtonQButtonMediumQSecondInfo
            {
                get
                {
                    return _buttonqbuttonqbuttonmediumqsecondInfo;
                }
            }

            /// <summary>
            /// The LrContainer item.
            /// </summary>
            [RepositoryItem("bbdee348-37f4-4fbb-a9a7-28dd89493408")]
            public virtual Ranorex.DivTag LrContainer
            {
                get
                {
                    return _lrcontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The LrContainer item info.
            /// </summary>
            [RepositoryItemInfo("bbdee348-37f4-4fbb-a9a7-28dd89493408")]
            public virtual RepoItemInfo LrContainerInfo
            {
                get
                {
                    return _lrcontainerInfo;
                }
            }

            /// <summary>
            /// The SocialAccountLoginButtons item.
            /// </summary>
            [RepositoryItem("8cf1c64a-c897-4d33-9615-0e1e028f6f49")]
            public virtual Ranorex.DivTag SocialAccountLoginButtons
            {
                get
                {
                    return _socialaccountloginbuttonsInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SocialAccountLoginButtons item info.
            /// </summary>
            [RepositoryItemInfo("8cf1c64a-c897-4d33-9615-0e1e028f6f49")]
            public virtual RepoItemInfo SocialAccountLoginButtonsInfo
            {
                get
                {
                    return _socialaccountloginbuttonsInfo;
                }
            }
        }

        /// <summary>
        /// The PbWrapper1Folder folder.
        /// </summary>
        [RepositoryFolder("c8f40d99-e09b-4bc4-ae56-9d08a478505e")]
        public partial class PbWrapper1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _pbwrapperInfo;
            RepoItemInfo _pbbasketitemInfo;
            RepoItemInfo _pbbasketitem1Info;

            /// <summary>
            /// Creates a new PbWrapper1  folder.
            /// </summary>
            public PbWrapper1Folder(RepoGenBaseFolder parentFolder) :
                    base("PbWrapper1", ".//div[#'pb-container']/div", parentFolder, 30000, null, false, "c8f40d99-e09b-4bc4-ae56-9d08a478505e", "")
            {
                _pbwrapperInfo = new RepoItemInfo(this, "PbWrapper", "", "", 30000, null, "7c1bcd6c-3a03-4aab-a061-819e3ed0956f");
                _pbbasketitemInfo = new RepoItemInfo(this, "PbBasketItem", "div[3]/div[3]", "div[3]/div[3]", 30000, null, "228d1912-7d35-4460-a2f6-3ecce5ea8c3e");
                _pbbasketitem1Info = new RepoItemInfo(this, "PbBasketItem1", "div[4]/div[2]", "div[4]/div[2]", 30000, null, "bd4b547d-dc4b-4e62-88cd-6df789659d25");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c8f40d99-e09b-4bc4-ae56-9d08a478505e")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c8f40d99-e09b-4bc4-ae56-9d08a478505e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PbWrapper item.
            /// </summary>
            [RepositoryItem("7c1bcd6c-3a03-4aab-a061-819e3ed0956f")]
            public virtual Ranorex.DivTag PbWrapper
            {
                get
                {
                    return _pbwrapperInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PbWrapper item info.
            /// </summary>
            [RepositoryItemInfo("7c1bcd6c-3a03-4aab-a061-819e3ed0956f")]
            public virtual RepoItemInfo PbWrapperInfo
            {
                get
                {
                    return _pbwrapperInfo;
                }
            }

            /// <summary>
            /// The PbBasketItem item.
            /// </summary>
            [RepositoryItem("228d1912-7d35-4460-a2f6-3ecce5ea8c3e")]
            public virtual Ranorex.DivTag PbBasketItem
            {
                get
                {
                    return _pbbasketitemInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PbBasketItem item info.
            /// </summary>
            [RepositoryItemInfo("228d1912-7d35-4460-a2f6-3ecce5ea8c3e")]
            public virtual RepoItemInfo PbBasketItemInfo
            {
                get
                {
                    return _pbbasketitemInfo;
                }
            }

            /// <summary>
            /// The PbBasketItem1 item.
            /// </summary>
            [RepositoryItem("bd4b547d-dc4b-4e62-88cd-6df789659d25")]
            public virtual Ranorex.DivTag PbBasketItem1
            {
                get
                {
                    return _pbbasketitem1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The PbBasketItem1 item info.
            /// </summary>
            [RepositoryItemInfo("bd4b547d-dc4b-4e62-88cd-6df789659d25")]
            public virtual RepoItemInfo PbBasketItem1Info
            {
                get
                {
                    return _pbbasketitem1Info;
                }
            }
        }

        /// <summary>
        /// The NewIncognitoTabGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("7d074ade-a53c-4d63-a0ae-4a6a2e9de501")]
        public partial class NewIncognitoTabGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _paneInfo;
            RepoItemInfo _element367825152Info;
            RepoItemInfo _element367989952Info;
            RepoItemInfo _backInfo;

            /// <summary>
            /// Creates a new NewIncognitoTabGoogleChrome  folder.
            /// </summary>
            public NewIncognitoTabGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NewIncognitoTabGoogleChrome", "/form[@title>'New Incognito Tab - Google']", parentFolder, 30000, null, true, "7d074ade-a53c-4d63-a0ae-4a6a2e9de501", "")
            {
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename>'trendyol - Google''da Ara -']/container[@accessiblename='Google Chrome']//tabpagelist[@accessiblerole='PageTabList']/container[2]", ".//tabpagelist/container[2]", 30000, null, "890f63d2-0581-410b-99ae-ba21d627d18a");
                _element367825152Info = new RepoItemInfo(this, "Element367825152", "element[@automationid='367825152']", "element[@automationid='367825152']", 30000, null, "c4b9c442-9923-49ae-ab69-c3a478359cdc");
                _element367989952Info = new RepoItemInfo(this, "Element367989952", "element[@automationid='367989952']", "element[@automationid='367989952']", 30000, null, "91978332-69c4-49a6-af32-7203db539307");
                _backInfo = new RepoItemInfo(this, "Back", "container[@accessiblename>'Kadın Butikleri, Yeni Sezon']/container[@accessiblename='Google Chrome']/container/container[2]/container[1]/toolbar[1]/button[@accessiblename='Back']", ".//button[@accessiblename='Back']", 30000, null, "b61814bc-1d25-48f5-b849-acf691dbd9c5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7d074ade-a53c-4d63-a0ae-4a6a2e9de501")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7d074ade-a53c-4d63-a0ae-4a6a2e9de501")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("890f63d2-0581-410b-99ae-ba21d627d18a")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("890f63d2-0581-410b-99ae-ba21d627d18a")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }

            /// <summary>
            /// The Element367825152 item.
            /// </summary>
            [RepositoryItem("c4b9c442-9923-49ae-ab69-c3a478359cdc")]
            public virtual Ranorex.Unknown Element367825152
            {
                get
                {
                    return _element367825152Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element367825152 item info.
            /// </summary>
            [RepositoryItemInfo("c4b9c442-9923-49ae-ab69-c3a478359cdc")]
            public virtual RepoItemInfo Element367825152Info
            {
                get
                {
                    return _element367825152Info;
                }
            }

            /// <summary>
            /// The Element367989952 item.
            /// </summary>
            [RepositoryItem("91978332-69c4-49a6-af32-7203db539307")]
            public virtual Ranorex.Unknown Element367989952
            {
                get
                {
                    return _element367989952Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element367989952 item info.
            /// </summary>
            [RepositoryItemInfo("91978332-69c4-49a6-af32-7203db539307")]
            public virtual RepoItemInfo Element367989952Info
            {
                get
                {
                    return _element367989952Info;
                }
            }

            /// <summary>
            /// The Back item.
            /// </summary>
            [RepositoryItem("b61814bc-1d25-48f5-b849-acf691dbd9c5")]
            public virtual Ranorex.Button Back
            {
                get
                {
                    return _backInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Back item info.
            /// </summary>
            [RepositoryItemInfo("b61814bc-1d25-48f5-b849-acf691dbd9c5")]
            public virtual RepoItemInfo BackInfo
            {
                get
                {
                    return _backInfo;
                }
            }
        }

        /// <summary>
        /// The KadınButikleriYeniSezonUEruenleriAppFolder folder.
        /// </summary>
        [RepositoryFolder("6efdd5f2-e3f9-4a05-8fbc-8e5e324b6692")]
        public partial class KadınButikleriYeniSezonUEruenleriAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _element359900672Info;

            /// <summary>
            /// Creates a new KadınButikleriYeniSezonUEruenleri  folder.
            /// </summary>
            public KadınButikleriYeniSezonUEruenleriAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KadınButikleriYeniSezonUEruenleri", "/form[@title>'Kadın Butikleri, Yeni Sezon']", parentFolder, 30000, null, true, "6efdd5f2-e3f9-4a05-8fbc-8e5e324b6692", "")
            {
                _element359900672Info = new RepoItemInfo(this, "Element359900672", "element[@automationid='359900672']", "element[@automationid='359900672']", 30000, null, "435f9dc3-7657-4bc9-9dad-144bb7c71935");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6efdd5f2-e3f9-4a05-8fbc-8e5e324b6692")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6efdd5f2-e3f9-4a05-8fbc-8e5e324b6692")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Element359900672 item.
            /// </summary>
            [RepositoryItem("435f9dc3-7657-4bc9-9dad-144bb7c71935")]
            public virtual Ranorex.Unknown Element359900672
            {
                get
                {
                    return _element359900672Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element359900672 item info.
            /// </summary>
            [RepositoryItemInfo("435f9dc3-7657-4bc9-9dad-144bb7c71935")]
            public virtual RepoItemInfo Element359900672Info
            {
                get
                {
                    return _element359900672Info;
                }
            }
        }

        /// <summary>
        /// The EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder folder.
        /// </summary>
        [RepositoryFolder("59902057-57e5-4852-9d90-3c428cc4bb45")]
        public partial class EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _element221778240Info;
            RepoItemInfo _paneInfo;
            RepoItemInfo _backInfo;
            RepoItemInfo _girişyapInfo;
            RepoItemInfo _documentInfo;
            RepoItemInfo _groupingInfo;
            RepoItemInfo _hesabımInfo;
            RepoItemInfo _grouping1Info;
            RepoItemInfo _grouping2Info;

            /// <summary>
            /// Creates a new EnTrendUEruenlerTuerkiyeninOnlineAl  folder.
            /// </summary>
            public EnTrendUEruenlerTuerkiyeninOnlineAlAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EnTrendUEruenlerTuerkiyeninOnlineAl", "/form[@title>'En Trend Ürünler Türkiye''nin']", parentFolder, 30000, null, true, "59902057-57e5-4852-9d90-3c428cc4bb45", "")
            {
                _element221778240Info = new RepoItemInfo(this, "Element221778240", "element[@automationid='221778240']", "element[@automationid='221778240']", 30000, null, "43562fa7-4cf7-445c-a47a-3ce78c28c60d");
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[@accessiblename='Google Chrome']/container/container[2]/container[1]", "?/?/container[@accessiblename='Google Chrome']/container[@accessiblerole='Pane']/container[2]/container[1]", 30000, null, "8a25c8e7-89da-4638-8d01-66b35239e0a1");
                _backInfo = new RepoItemInfo(this, "Back", "container[@accessiblename>'https://www.trendyol.com/']/container[@accessiblename='Google Chrome']//toolbar[@accessiblerole='ToolBar']/button[@accessiblename='Back']", ".//button[@accessiblename='Back']", 30000, null, "11714865-c1ad-47e8-8ecb-bc119ad7557f");
                _girişyapInfo = new RepoItemInfo(this, "GirişYap", "element[@automationid='16736768']/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[1]/container[1]/container/container[@accessiblerole='Grouping']/container[2]/container/container[1]//text[@accessiblename='Giriş Yap']", ".//text[@accessiblename='Giriş Yap']", 30000, null, "ebd21a27-a53a-4b48-9540-0af746be9b88");
                _documentInfo = new RepoItemInfo(this, "Document", "?/?/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[1]/container[3]/container[1]", "?/?/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[1]/container[3]/container[1]", 30000, null, "9a0611a8-c1a5-4d63-a4ff-d5b6fedb5810");
                _groupingInfo = new RepoItemInfo(this, "Grouping", "element[@automationid='50213120']/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[1]/container[1]/container/container[@accessiblerole='Grouping']/container[2]/container/container[1]/container[1]", "?/?/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[1]/container[1]/container[@accessiblerole='Grouping']/container[@accessiblerole='Grouping']/container[2]/container[@accessiblerole='Grouping']/container[1]/container[1]", 30000, null, "cecc687c-0c6e-4872-90d9-7e6a15aaaf4b");
                _hesabımInfo = new RepoItemInfo(this, "Hesabım", "element[@automationid='481092992']/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[1]/container[1]/container/container[@accessiblerole='Grouping']/container[2]/container/container[1]//text[@accessiblename='Hesabım']", ".//text[@accessiblename='Hesabım']", 30000, null, "8423f058-e5f8-4b9a-aa5d-f60ffeb8d649");
                _grouping1Info = new RepoItemInfo(this, "Grouping1", "element[@automationid='481092992']/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[1]/container[1]/container/container[@accessiblerole='Grouping']/container[2]/container/container[1]/container[@accessiblerole='Grouping']", "?/?/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[1]/container[1]/container[@accessiblerole='Grouping']/container[@accessiblerole='Grouping']/container[2]/container[@accessiblerole='Grouping']/container[1]/container[@accessiblerole='Grouping']", 30000, null, "ea9ba47e-55a4-48e9-badb-adaf5bbba342");
                _grouping2Info = new RepoItemInfo(this, "Grouping2", "?/?/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[1]/container[3]", "?/?/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[1]/container[3]", 30000, null, "84efefe9-6b4e-48cc-b05f-19d9a99855c8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("59902057-57e5-4852-9d90-3c428cc4bb45")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("59902057-57e5-4852-9d90-3c428cc4bb45")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Element221778240 item.
            /// </summary>
            [RepositoryItem("43562fa7-4cf7-445c-a47a-3ce78c28c60d")]
            public virtual Ranorex.Unknown Element221778240
            {
                get
                {
                    return _element221778240Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element221778240 item info.
            /// </summary>
            [RepositoryItemInfo("43562fa7-4cf7-445c-a47a-3ce78c28c60d")]
            public virtual RepoItemInfo Element221778240Info
            {
                get
                {
                    return _element221778240Info;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("8a25c8e7-89da-4638-8d01-66b35239e0a1")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("8a25c8e7-89da-4638-8d01-66b35239e0a1")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }

            /// <summary>
            /// The Back item.
            /// </summary>
            [RepositoryItem("11714865-c1ad-47e8-8ecb-bc119ad7557f")]
            public virtual Ranorex.Button Back
            {
                get
                {
                    return _backInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Back item info.
            /// </summary>
            [RepositoryItemInfo("11714865-c1ad-47e8-8ecb-bc119ad7557f")]
            public virtual RepoItemInfo BackInfo
            {
                get
                {
                    return _backInfo;
                }
            }

            /// <summary>
            /// The GirişYap item.
            /// </summary>
            [RepositoryItem("ebd21a27-a53a-4b48-9540-0af746be9b88")]
            public virtual Ranorex.Text GirişYap
            {
                get
                {
                    return _girişyapInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The GirişYap item info.
            /// </summary>
            [RepositoryItemInfo("ebd21a27-a53a-4b48-9540-0af746be9b88")]
            public virtual RepoItemInfo GirişYapInfo
            {
                get
                {
                    return _girişyapInfo;
                }
            }

            /// <summary>
            /// The Document item.
            /// </summary>
            [RepositoryItem("9a0611a8-c1a5-4d63-a4ff-d5b6fedb5810")]
            public virtual Ranorex.Container Document
            {
                get
                {
                    return _documentInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Document item info.
            /// </summary>
            [RepositoryItemInfo("9a0611a8-c1a5-4d63-a4ff-d5b6fedb5810")]
            public virtual RepoItemInfo DocumentInfo
            {
                get
                {
                    return _documentInfo;
                }
            }

            /// <summary>
            /// The Grouping item.
            /// </summary>
            [RepositoryItem("cecc687c-0c6e-4872-90d9-7e6a15aaaf4b")]
            public virtual Ranorex.Container Grouping
            {
                get
                {
                    return _groupingInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Grouping item info.
            /// </summary>
            [RepositoryItemInfo("cecc687c-0c6e-4872-90d9-7e6a15aaaf4b")]
            public virtual RepoItemInfo GroupingInfo
            {
                get
                {
                    return _groupingInfo;
                }
            }

            /// <summary>
            /// The Hesabım item.
            /// </summary>
            [RepositoryItem("8423f058-e5f8-4b9a-aa5d-f60ffeb8d649")]
            public virtual Ranorex.Text Hesabım
            {
                get
                {
                    return _hesabımInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Hesabım item info.
            /// </summary>
            [RepositoryItemInfo("8423f058-e5f8-4b9a-aa5d-f60ffeb8d649")]
            public virtual RepoItemInfo HesabımInfo
            {
                get
                {
                    return _hesabımInfo;
                }
            }

            /// <summary>
            /// The Grouping1 item.
            /// </summary>
            [RepositoryItem("ea9ba47e-55a4-48e9-badb-adaf5bbba342")]
            public virtual Ranorex.Container Grouping1
            {
                get
                {
                    return _grouping1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Grouping1 item info.
            /// </summary>
            [RepositoryItemInfo("ea9ba47e-55a4-48e9-badb-adaf5bbba342")]
            public virtual RepoItemInfo Grouping1Info
            {
                get
                {
                    return _grouping1Info;
                }
            }

            /// <summary>
            /// The Grouping2 item.
            /// </summary>
            [RepositoryItem("84efefe9-6b4e-48cc-b05f-19d9a99855c8")]
            public virtual Ranorex.Container Grouping2
            {
                get
                {
                    return _grouping2Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Grouping2 item info.
            /// </summary>
            [RepositoryItemInfo("84efefe9-6b4e-48cc-b05f-19d9a99855c8")]
            public virtual RepoItemInfo Grouping2Info
            {
                get
                {
                    return _grouping2Info;
                }
            }
        }

        /// <summary>
        /// The HttpsWwwTrendyolComUyelikcbEqhttpsAppFolder folder.
        /// </summary>
        [RepositoryFolder("ed9dd564-d49e-46a2-96ac-41322745723e")]
        public partial class HttpsWwwTrendyolComUyelikcbEqhttpsAppFolder : RepoGenBaseFolder
        {
            RonwellTaskRepositoryFolders.Grouping1Folder _grouping1;
            RepoItemInfo _paneInfo;
            RepoItemInfo _element180987456Info;
            RepoItemInfo _ueyeolInfo;
            RepoItemInfo _groupingInfo;
            RepoItemInfo _grouping2Info;
            RepoItemInfo _sometextInfo;
            RepoItemInfo _backInfo;
            RepoItemInfo _back1Info;

            /// <summary>
            /// Creates a new HttpsWwwTrendyolComUyelikcbEqhttps  folder.
            /// </summary>
            public HttpsWwwTrendyolComUyelikcbEqhttpsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpsWwwTrendyolComUyelikcbEqhttps", "/form[@title>'https://www.trendyol.com/']", parentFolder, 30000, null, true, "ed9dd564-d49e-46a2-96ac-41322745723e", "")
            {
                _grouping1 = new RonwellTaskRepositoryFolders.Grouping1Folder(this);
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename>'https://www.trendyol.com/']/container[@accessiblename='Google Chrome']/container/container[2]/container[1]", "?/?/container[@accessiblename='Google Chrome']/container[@accessiblerole='Pane']/container[2]/container[1]", 30000, null, "e57c503c-8e1d-4cf4-ab31-cc76842b5bfe");
                _element180987456Info = new RepoItemInfo(this, "Element180987456", "element[@automationid='180987456']", "element[@automationid='180987456']", 30000, null, "d725e271-e357-4a29-8e90-2cae4ddc1ac6");
                _ueyeolInfo = new RepoItemInfo(this, "UEyeOl", "element/container[@accessiblerole='Document']/container[1]/container[3]/button[@accessiblename='Üye Ol']", ".//button[@accessiblename='Üye Ol']", 30000, null, "c7410d14-6366-4d09-b678-cce505dd4881");
                _groupingInfo = new RepoItemInfo(this, "Grouping", "element[@automationid='297962944']/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[1]/container[1]/container/container[@accessiblerole='Grouping']/container[2]/container/container[1]/container[1]", "?/?/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[1]/container[1]/container[@accessiblerole='Grouping']/container[@accessiblerole='Grouping']/container[2]/container[@accessiblerole='Grouping']/container[1]/container[1]", 30000, null, "f9826389-8d10-4d0d-9a74-844481549b4b");
                _grouping2Info = new RepoItemInfo(this, "Grouping2", "element[@automationid='297962944']/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[1]/container[1]/container/container[@accessiblerole='Grouping']/container[2]/container/container[1]/container[@accessiblerole='Grouping']", "?/?/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[1]/container[1]/container[@accessiblerole='Grouping']/container[@accessiblerole='Grouping']/container[2]/container[@accessiblerole='Grouping']/container[1]/container[@accessiblerole='Grouping']", 30000, null, "6e1315e6-f325-46bb-ba1d-4cabdc0c814e");
                _sometextInfo = new RepoItemInfo(this, "SomeText", "element[@automationid='305291136']/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[1]/container[1]/container/container[@accessiblerole='Grouping']/container[2]/container/container[1]//text[@accessiblename='']", ".//text[@accessiblename='']", 30000, null, "c3133043-cc2e-4e6f-9654-ed2b615dcd60");
                _backInfo = new RepoItemInfo(this, "Back", "container[@accessiblename>'Trendyolmilla Pantolon Bol']/container[@accessiblename='Google Chrome']/container/container[2]/container[1]/toolbar[1]/button[@accessiblename='Back']", ".//button[@accessiblename='Back']", 30000, null, "62e07eb1-2ef9-47a9-b6bc-ed66727651d1");
                _back1Info = new RepoItemInfo(this, "Back1", "container[@accessiblename>'https://www.trendyol.com/']/container[@accessiblename='Google Chrome']/container/container[2]/container[1]/toolbar[1]/button[@accessiblename='Back']", ".//button[@accessiblename='Back']", 30000, null, "b23de63b-ff4d-4cef-80e4-68ac53db7093");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ed9dd564-d49e-46a2-96ac-41322745723e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ed9dd564-d49e-46a2-96ac-41322745723e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("e57c503c-8e1d-4cf4-ab31-cc76842b5bfe")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("e57c503c-8e1d-4cf4-ab31-cc76842b5bfe")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }

            /// <summary>
            /// The Element180987456 item.
            /// </summary>
            [RepositoryItem("d725e271-e357-4a29-8e90-2cae4ddc1ac6")]
            public virtual Ranorex.Unknown Element180987456
            {
                get
                {
                    return _element180987456Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element180987456 item info.
            /// </summary>
            [RepositoryItemInfo("d725e271-e357-4a29-8e90-2cae4ddc1ac6")]
            public virtual RepoItemInfo Element180987456Info
            {
                get
                {
                    return _element180987456Info;
                }
            }

            /// <summary>
            /// The UEyeOl item.
            /// </summary>
            [RepositoryItem("c7410d14-6366-4d09-b678-cce505dd4881")]
            public virtual Ranorex.Button UEyeOl
            {
                get
                {
                    return _ueyeolInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The UEyeOl item info.
            /// </summary>
            [RepositoryItemInfo("c7410d14-6366-4d09-b678-cce505dd4881")]
            public virtual RepoItemInfo UEyeOlInfo
            {
                get
                {
                    return _ueyeolInfo;
                }
            }

            /// <summary>
            /// The Grouping item.
            /// </summary>
            [RepositoryItem("f9826389-8d10-4d0d-9a74-844481549b4b")]
            public virtual Ranorex.Container Grouping
            {
                get
                {
                    return _groupingInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Grouping item info.
            /// </summary>
            [RepositoryItemInfo("f9826389-8d10-4d0d-9a74-844481549b4b")]
            public virtual RepoItemInfo GroupingInfo
            {
                get
                {
                    return _groupingInfo;
                }
            }

            /// <summary>
            /// The Grouping2 item.
            /// </summary>
            [RepositoryItem("6e1315e6-f325-46bb-ba1d-4cabdc0c814e")]
            public virtual Ranorex.Container Grouping2
            {
                get
                {
                    return _grouping2Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Grouping2 item info.
            /// </summary>
            [RepositoryItemInfo("6e1315e6-f325-46bb-ba1d-4cabdc0c814e")]
            public virtual RepoItemInfo Grouping2Info
            {
                get
                {
                    return _grouping2Info;
                }
            }

            /// <summary>
            /// The SomeText item.
            /// </summary>
            [RepositoryItem("c3133043-cc2e-4e6f-9654-ed2b615dcd60")]
            public virtual Ranorex.Text SomeText
            {
                get
                {
                    return _sometextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText item info.
            /// </summary>
            [RepositoryItemInfo("c3133043-cc2e-4e6f-9654-ed2b615dcd60")]
            public virtual RepoItemInfo SomeTextInfo
            {
                get
                {
                    return _sometextInfo;
                }
            }

            /// <summary>
            /// The Back item.
            /// </summary>
            [RepositoryItem("62e07eb1-2ef9-47a9-b6bc-ed66727651d1")]
            public virtual Ranorex.Button Back
            {
                get
                {
                    return _backInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Back item info.
            /// </summary>
            [RepositoryItemInfo("62e07eb1-2ef9-47a9-b6bc-ed66727651d1")]
            public virtual RepoItemInfo BackInfo
            {
                get
                {
                    return _backInfo;
                }
            }

            /// <summary>
            /// The Back1 item.
            /// </summary>
            [RepositoryItem("b23de63b-ff4d-4cef-80e4-68ac53db7093")]
            public virtual Ranorex.Button Back1
            {
                get
                {
                    return _back1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Back1 item info.
            /// </summary>
            [RepositoryItemInfo("b23de63b-ff4d-4cef-80e4-68ac53db7093")]
            public virtual RepoItemInfo Back1Info
            {
                get
                {
                    return _back1Info;
                }
            }

            /// <summary>
            /// The Grouping1 folder.
            /// </summary>
            [RepositoryFolder("220bfdab-912b-44df-8006-624d5882d1e1")]
            public virtual RonwellTaskRepositoryFolders.Grouping1Folder Grouping1
            {
                get { return _grouping1; }
            }
        }

        /// <summary>
        /// The Grouping1Folder folder.
        /// </summary>
        [RepositoryFolder("220bfdab-912b-44df-8006-624d5882d1e1")]
        public partial class Grouping1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _groupingInfo;
            RepoItemInfo _erkekInfo;
            RepoItemInfo _ueyeolInfo;
            RepoItemInfo _comboboxInfo;
            RepoItemInfo _textInfo;

            /// <summary>
            /// Creates a new Grouping1  folder.
            /// </summary>
            public Grouping1Folder(RepoGenBaseFolder parentFolder) :
                    base("Grouping1", "element/container[@accessiblerole='Document']/container[1]/container[3]/container[3]", parentFolder, 30000, null, false, "220bfdab-912b-44df-8006-624d5882d1e1", "")
            {
                _groupingInfo = new RepoItemInfo(this, "Grouping", "", "", 30000, null, "fabaeabc-83f6-4a0e-9a26-96d73ee78f3d");
                _erkekInfo = new RepoItemInfo(this, "Erkek", "button[@accessiblename='Erkek']", "", 30000, null, "090ba22c-a154-4d37-936d-4576aa8cc1f1");
                _ueyeolInfo = new RepoItemInfo(this, "UEYEOL", "button[@accessiblename='ÜYE OL']", "", 30000, null, "3e06a20e-cd95-4a93-9f21-9191e918ef01");
                _comboboxInfo = new RepoItemInfo(this, "ComboBox", "combobox[@accessiblerole='ComboBox']", "", 30000, null, "348c57a7-7b84-41c8-bcef-c9d31b0f80d9");
                _textInfo = new RepoItemInfo(this, "Text", "container[1]/text[2]", "container[1]/text[2]", 30000, null, "7e4234d6-41bb-48f6-baf6-1f12505e9912");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("220bfdab-912b-44df-8006-624d5882d1e1")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("220bfdab-912b-44df-8006-624d5882d1e1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Grouping item.
            /// </summary>
            [RepositoryItem("fabaeabc-83f6-4a0e-9a26-96d73ee78f3d")]
            public virtual Ranorex.Container Grouping
            {
                get
                {
                    return _groupingInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Grouping item info.
            /// </summary>
            [RepositoryItemInfo("fabaeabc-83f6-4a0e-9a26-96d73ee78f3d")]
            public virtual RepoItemInfo GroupingInfo
            {
                get
                {
                    return _groupingInfo;
                }
            }

            /// <summary>
            /// The Erkek item.
            /// </summary>
            [RepositoryItem("090ba22c-a154-4d37-936d-4576aa8cc1f1")]
            public virtual Ranorex.Button Erkek
            {
                get
                {
                    return _erkekInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Erkek item info.
            /// </summary>
            [RepositoryItemInfo("090ba22c-a154-4d37-936d-4576aa8cc1f1")]
            public virtual RepoItemInfo ErkekInfo
            {
                get
                {
                    return _erkekInfo;
                }
            }

            /// <summary>
            /// The UEYEOL item.
            /// </summary>
            [RepositoryItem("3e06a20e-cd95-4a93-9f21-9191e918ef01")]
            public virtual Ranorex.Button UEYEOL
            {
                get
                {
                    return _ueyeolInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The UEYEOL item info.
            /// </summary>
            [RepositoryItemInfo("3e06a20e-cd95-4a93-9f21-9191e918ef01")]
            public virtual RepoItemInfo UEYEOLInfo
            {
                get
                {
                    return _ueyeolInfo;
                }
            }

            /// <summary>
            /// The ComboBox item.
            /// </summary>
            [RepositoryItem("348c57a7-7b84-41c8-bcef-c9d31b0f80d9")]
            public virtual Ranorex.ComboBox ComboBox
            {
                get
                {
                    return _comboboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox item info.
            /// </summary>
            [RepositoryItemInfo("348c57a7-7b84-41c8-bcef-c9d31b0f80d9")]
            public virtual RepoItemInfo ComboBoxInfo
            {
                get
                {
                    return _comboboxInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("7e4234d6-41bb-48f6-baf6-1f12505e9912")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("7e4234d6-41bb-48f6-baf6-1f12505e9912")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }
        }

        /// <summary>
        /// The ErkekButikleriYeniSezonUEruenlerAppFolder folder.
        /// </summary>
        [RepositoryFolder("1171294e-7dde-4fa0-975e-c625dc7ac3a4")]
        public partial class ErkekButikleriYeniSezonUEruenlerAppFolder : RepoGenBaseFolder
        {
            RonwellTaskRepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlFolder1 _entrendueruenlertuerkiyeninonlineal;
            RonwellTaskRepositoryFolders.OEdemeTrendyolFolder _oedemetrendyol;
            RepoItemInfo _graphicInfo;
            RepoItemInfo _graphic1Info;
            RepoItemInfo _sometextInfo;
            RepoItemInfo _backInfo;
            RepoItemInfo _favorilerimInfo;
            RepoItemInfo _groupingInfo;
            RepoItemInfo _graphic4Info;
            RepoItemInfo _none2Info;
            RepoItemInfo _link75tlveuezerikargobedavaInfo;
            RepoItemInfo _sepetimInfo;
            RepoItemInfo _sepetionaylaInfo;
            RepoItemInfo _kaydetvedevametInfo;
            RepoItemInfo _grouping1Info;

            /// <summary>
            /// Creates a new ErkekButikleriYeniSezonUEruenler  folder.
            /// </summary>
            public ErkekButikleriYeniSezonUEruenlerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ErkekButikleriYeniSezonUEruenler", "/form[@title>'Erkek Butikleri, Yeni Sezon']", parentFolder, 30000, null, true, "1171294e-7dde-4fa0-975e-c625dc7ac3a4", "")
            {
                _entrendueruenlertuerkiyeninonlineal = new RonwellTaskRepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlFolder1(this);
                _oedemetrendyol = new RonwellTaskRepositoryFolders.OEdemeTrendyolFolder(this);
                _graphicInfo = new RepoItemInfo(this, "Graphic", "?/?/container[@accessiblename>'Erkek Butikleri, Yeni Sezon']/container[1]/container[3]/container[1]//link[@accessiblename='Sana Özel']/picture[@accessiblerole='Graphic']", ".//link[@accessiblename='Sana Özel']/picture[@accessiblerole='Graphic']", 30000, null, "34df74c7-14b2-43eb-aeba-b4f48e776704");
                _graphic1Info = new RepoItemInfo(this, "Graphic1", "?/?/container[@accessiblename>'Kadın Butikleri, Yeni Sezon']/container[1]/container[3]/container[1]//link[@accessiblename='Sana Özel']/picture[@accessiblerole='Graphic']", ".//link[@accessiblename='Sana Özel']/picture[@accessiblerole='Graphic']", 30000, null, "c6ed5ce1-f9e1-46c1-b225-3b530b48d524");
                _sometextInfo = new RepoItemInfo(this, "SomeText", "?/?/container[@accessiblename>'Ronic Nutrition Isolate Whey']/container[1]/container[4]/container[7]/?/?/button[@accessiblename='']/?/?/text[@accessiblename='']", ".//button[@accessiblename='']/container[@accessiblerole='Grouping']/text[@accessiblename='']", 30000, null, "661215fc-f8de-4826-9379-5088125754ed");
                _backInfo = new RepoItemInfo(this, "Back", "container[@accessiblename>'Monopoly Klasik - Er022.1009']/container[@accessiblename='Google Chrome']//toolbar[@accessiblerole='ToolBar']/button[@accessiblename='Back']", ".//button[@accessiblename='Back']", 30000, null, "b410bfc9-a28c-4426-899d-6bf59411ac74");
                _favorilerimInfo = new RepoItemInfo(this, "Favorilerim", "element[@automationid='481092992']/container[@accessiblename>'Corsair Vengeance RGB Pro']/container[1]/container[1]/container/container[@accessiblerole='Grouping']/container[2]/?/?/link[@accessiblename='  Favorilerim']//text[@accessiblename='Favorilerim']", ".//text[@accessiblename='Favorilerim']", 30000, null, "14cc1a6b-88f6-44a4-9f81-d3b3ce9c05a8");
                _groupingInfo = new RepoItemInfo(this, "Grouping", "element[@automationid='481092992']/container[@accessiblename='Favoriler - Trendyol']/container/container[1]/container[3]", ".//container[@accessiblerole='Grouping']/container[1]/container[3]", 30000, null, "0a1f534a-d827-4e51-8bd1-f014fc830b2b");
                _graphic4Info = new RepoItemInfo(this, "Graphic4", "?/?/container[@accessiblename>'En Trend Ürünler Türkiye''nin']/container[1]/container[3]/container[1]//link[@accessiblename='Sana Özel']/picture[@accessiblerole='Graphic']", ".//link[@accessiblename='Sana Özel']/picture[@accessiblerole='Graphic']", 30000, null, "0ee3c317-c4dd-4130-a61d-53e342a51ca2");
                _none2Info = new RepoItemInfo(this, "None2", "?/?/container/?/?/container", ".//container", 30000, null, "5a5b5399-5738-41b3-8d56-72e40da6a00a");
                _link75tlveuezerikargobedavaInfo = new RepoItemInfo(this, "Link75TLVeUEzeriKargoBedava", "?/?/container[@accessiblename>'Corsair Vengeance RGB Pro']/container[1]/container[4]/container[15]//link[@accessiblename>' 75 TL ve Üzeri Kargo Bedava']", ".//link[@accessiblename>' 75 TL ve Üzeri Kargo Bedava']", 30000, null, "2d223606-e3ac-4735-979b-4b2811244655");
                _sepetimInfo = new RepoItemInfo(this, "Sepetim", "element[@automationid='481092992']/container[@accessiblename>'Corsair Vengeance RGB Pro']/container[1]/container[1]/container/container[@accessiblerole='Grouping']/container[2]//link[@accessiblename='  Sepetim 2']/?/?/text[@accessiblename='Sepetim']", ".//text[@accessiblename='Sepetim']", 30000, null, "b3642bec-7523-4ceb-a48e-941b86538640");
                _sepetionaylaInfo = new RepoItemInfo(this, "SepetiOnayla", "?/?/container[@accessiblename='Sepetim - Trendyol']/container[1]/container[3]/container[@accessiblerole='Grouping']/container[30]/link[2]/text[@accessiblename='Sepeti Onayla']", "?/?/container[@accessiblename='Sepetim - Trendyol']/container[1]/container[3]/container[@accessiblerole='Grouping']/container[30]/link[2]/text[@accessiblename='Sepeti Onayla']", 30000, null, "0195a3eb-6cee-4f77-9678-00a112d7b270");
                _kaydetvedevametInfo = new RepoItemInfo(this, "KaydetVeDevamEt", "?/?/container[@accessiblename='Ödeme - Trendyol']/container/container[1]/container[1]/container[3]/container[3]/container[5]/button[@accessiblename='Kaydet ve Devam Et']", ".//container[@accessiblerole='Grouping']/container[1]/container[3]/container[3]/container[5]/button[@accessiblename='Kaydet ve Devam Et']", 30000, null, "95dcb0c2-f72b-4f1a-862d-f7e81cd1b749");
                _grouping1Info = new RepoItemInfo(this, "Grouping1", "?/?/container[@accessiblename='Ödeme - Trendyol']/container/container[1]/container[1]", ".//container[@accessiblerole='Grouping']/container[1]", 30000, null, "070b2b39-e57a-4ba3-8e07-5e65fe0a5c75");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1171294e-7dde-4fa0-975e-c625dc7ac3a4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1171294e-7dde-4fa0-975e-c625dc7ac3a4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Graphic item.
            /// </summary>
            [RepositoryItem("34df74c7-14b2-43eb-aeba-b4f48e776704")]
            public virtual Ranorex.Picture Graphic
            {
                get
                {
                    return _graphicInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The Graphic item info.
            /// </summary>
            [RepositoryItemInfo("34df74c7-14b2-43eb-aeba-b4f48e776704")]
            public virtual RepoItemInfo GraphicInfo
            {
                get
                {
                    return _graphicInfo;
                }
            }

            /// <summary>
            /// The Graphic1 item.
            /// </summary>
            [RepositoryItem("c6ed5ce1-f9e1-46c1-b225-3b530b48d524")]
            public virtual Ranorex.Picture Graphic1
            {
                get
                {
                    return _graphic1Info.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The Graphic1 item info.
            /// </summary>
            [RepositoryItemInfo("c6ed5ce1-f9e1-46c1-b225-3b530b48d524")]
            public virtual RepoItemInfo Graphic1Info
            {
                get
                {
                    return _graphic1Info;
                }
            }

            /// <summary>
            /// The SomeText item.
            /// </summary>
            [RepositoryItem("661215fc-f8de-4826-9379-5088125754ed")]
            public virtual Ranorex.Text SomeText
            {
                get
                {
                    return _sometextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText item info.
            /// </summary>
            [RepositoryItemInfo("661215fc-f8de-4826-9379-5088125754ed")]
            public virtual RepoItemInfo SomeTextInfo
            {
                get
                {
                    return _sometextInfo;
                }
            }

            /// <summary>
            /// The Back item.
            /// </summary>
            [RepositoryItem("b410bfc9-a28c-4426-899d-6bf59411ac74")]
            public virtual Ranorex.Button Back
            {
                get
                {
                    return _backInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Back item info.
            /// </summary>
            [RepositoryItemInfo("b410bfc9-a28c-4426-899d-6bf59411ac74")]
            public virtual RepoItemInfo BackInfo
            {
                get
                {
                    return _backInfo;
                }
            }

            /// <summary>
            /// The Favorilerim item.
            /// </summary>
            [RepositoryItem("14cc1a6b-88f6-44a4-9f81-d3b3ce9c05a8")]
            public virtual Ranorex.Text Favorilerim
            {
                get
                {
                    return _favorilerimInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Favorilerim item info.
            /// </summary>
            [RepositoryItemInfo("14cc1a6b-88f6-44a4-9f81-d3b3ce9c05a8")]
            public virtual RepoItemInfo FavorilerimInfo
            {
                get
                {
                    return _favorilerimInfo;
                }
            }

            /// <summary>
            /// The Grouping item.
            /// </summary>
            [RepositoryItem("0a1f534a-d827-4e51-8bd1-f014fc830b2b")]
            public virtual Ranorex.Container Grouping
            {
                get
                {
                    return _groupingInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Grouping item info.
            /// </summary>
            [RepositoryItemInfo("0a1f534a-d827-4e51-8bd1-f014fc830b2b")]
            public virtual RepoItemInfo GroupingInfo
            {
                get
                {
                    return _groupingInfo;
                }
            }

            /// <summary>
            /// The Graphic4 item.
            /// </summary>
            [RepositoryItem("0ee3c317-c4dd-4130-a61d-53e342a51ca2")]
            public virtual Ranorex.Picture Graphic4
            {
                get
                {
                    return _graphic4Info.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The Graphic4 item info.
            /// </summary>
            [RepositoryItemInfo("0ee3c317-c4dd-4130-a61d-53e342a51ca2")]
            public virtual RepoItemInfo Graphic4Info
            {
                get
                {
                    return _graphic4Info;
                }
            }

            /// <summary>
            /// The None2 item.
            /// </summary>
            [RepositoryItem("5a5b5399-5738-41b3-8d56-72e40da6a00a")]
            public virtual Ranorex.Container None2
            {
                get
                {
                    return _none2Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The None2 item info.
            /// </summary>
            [RepositoryItemInfo("5a5b5399-5738-41b3-8d56-72e40da6a00a")]
            public virtual RepoItemInfo None2Info
            {
                get
                {
                    return _none2Info;
                }
            }

            /// <summary>
            /// The Link75TLVeUEzeriKargoBedava item.
            /// </summary>
            [RepositoryItem("2d223606-e3ac-4735-979b-4b2811244655")]
            public virtual Ranorex.Link Link75TLVeUEzeriKargoBedava
            {
                get
                {
                    return _link75tlveuezerikargobedavaInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The Link75TLVeUEzeriKargoBedava item info.
            /// </summary>
            [RepositoryItemInfo("2d223606-e3ac-4735-979b-4b2811244655")]
            public virtual RepoItemInfo Link75TLVeUEzeriKargoBedavaInfo
            {
                get
                {
                    return _link75tlveuezerikargobedavaInfo;
                }
            }

            /// <summary>
            /// The Sepetim item.
            /// </summary>
            [RepositoryItem("b3642bec-7523-4ceb-a48e-941b86538640")]
            public virtual Ranorex.Text Sepetim
            {
                get
                {
                    return _sepetimInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Sepetim item info.
            /// </summary>
            [RepositoryItemInfo("b3642bec-7523-4ceb-a48e-941b86538640")]
            public virtual RepoItemInfo SepetimInfo
            {
                get
                {
                    return _sepetimInfo;
                }
            }

            /// <summary>
            /// The SepetiOnayla item.
            /// </summary>
            [RepositoryItem("0195a3eb-6cee-4f77-9678-00a112d7b270")]
            public virtual Ranorex.Text SepetiOnayla
            {
                get
                {
                    return _sepetionaylaInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SepetiOnayla item info.
            /// </summary>
            [RepositoryItemInfo("0195a3eb-6cee-4f77-9678-00a112d7b270")]
            public virtual RepoItemInfo SepetiOnaylaInfo
            {
                get
                {
                    return _sepetionaylaInfo;
                }
            }

            /// <summary>
            /// The KaydetVeDevamEt item.
            /// </summary>
            [RepositoryItem("95dcb0c2-f72b-4f1a-862d-f7e81cd1b749")]
            public virtual Ranorex.Button KaydetVeDevamEt
            {
                get
                {
                    return _kaydetvedevametInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The KaydetVeDevamEt item info.
            /// </summary>
            [RepositoryItemInfo("95dcb0c2-f72b-4f1a-862d-f7e81cd1b749")]
            public virtual RepoItemInfo KaydetVeDevamEtInfo
            {
                get
                {
                    return _kaydetvedevametInfo;
                }
            }

            /// <summary>
            /// The Grouping1 item.
            /// </summary>
            [RepositoryItem("070b2b39-e57a-4ba3-8e07-5e65fe0a5c75")]
            public virtual Ranorex.Container Grouping1
            {
                get
                {
                    return _grouping1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Grouping1 item info.
            /// </summary>
            [RepositoryItemInfo("070b2b39-e57a-4ba3-8e07-5e65fe0a5c75")]
            public virtual RepoItemInfo Grouping1Info
            {
                get
                {
                    return _grouping1Info;
                }
            }

            /// <summary>
            /// The EnTrendUEruenlerTuerkiyeninOnlineAl folder.
            /// </summary>
            [RepositoryFolder("2afb9358-ca46-4924-a02a-5ce114f74634")]
            public virtual RonwellTaskRepositoryFolders.EnTrendUEruenlerTuerkiyeninOnlineAlFolder1 EnTrendUEruenlerTuerkiyeninOnlineAl
            {
                get { return _entrendueruenlertuerkiyeninonlineal; }
            }

            /// <summary>
            /// The OEdemeTrendyol folder.
            /// </summary>
            [RepositoryFolder("f060c75b-fa82-47ad-9a20-f70c90bef24e")]
            public virtual RonwellTaskRepositoryFolders.OEdemeTrendyolFolder OEdemeTrendyol
            {
                get { return _oedemetrendyol; }
            }
        }

        /// <summary>
        /// The EnTrendUEruenlerTuerkiyeninOnlineAlFolder1 folder.
        /// </summary>
        [RepositoryFolder("2afb9358-ca46-4924-a02a-5ce114f74634")]
        public partial class EnTrendUEruenlerTuerkiyeninOnlineAlFolder1 : RepoGenBaseFolder
        {
            RepoItemInfo _documentInfo;
            RepoItemInfo _graphic2Info;
            RepoItemInfo _graphic3Info;

            /// <summary>
            /// Creates a new EnTrendUEruenlerTuerkiyeninOnlineAl  folder.
            /// </summary>
            public EnTrendUEruenlerTuerkiyeninOnlineAlFolder1(RepoGenBaseFolder parentFolder) :
                    base("EnTrendUEruenlerTuerkiyeninOnlineAl", "?/?/container[@accessiblerole='Document']", parentFolder, 30000, null, false, "2afb9358-ca46-4924-a02a-5ce114f74634", "")
            {
                _documentInfo = new RepoItemInfo(this, "Document", "", "", 30000, null, "d04044ce-3319-4f5b-962a-af60fd8db90a");
                _graphic2Info = new RepoItemInfo(this, "Graphic2", "container[1]/container[3]/container[2]/container[1]/link[@accessiblename>'HIZLI TESLİMAT KARGO BEDAVA']/picture[@accessiblerole='Graphic']", "", 30000, null, "90759b2e-114b-4f84-8276-51ad2c43662b");
                _graphic3Info = new RepoItemInfo(this, "Graphic3", "container[1]/container[3]/container[2]/container[2]/link[@accessiblename>'HIZLI TESLİMAT KARGO BEDAVA']/picture[@accessiblerole='Graphic']", "container[1]/container[3]/container[2]/container[2]/link[@accessiblename>'HIZLI TESLİMAT KARGO BEDAVA']/picture[@accessiblerole='Graphic']", 30000, null, "20a2ff18-8003-4eaa-9c1d-9694f37a0057");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2afb9358-ca46-4924-a02a-5ce114f74634")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2afb9358-ca46-4924-a02a-5ce114f74634")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Document item.
            /// </summary>
            [RepositoryItem("d04044ce-3319-4f5b-962a-af60fd8db90a")]
            public virtual Ranorex.Container Document
            {
                get
                {
                    return _documentInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Document item info.
            /// </summary>
            [RepositoryItemInfo("d04044ce-3319-4f5b-962a-af60fd8db90a")]
            public virtual RepoItemInfo DocumentInfo
            {
                get
                {
                    return _documentInfo;
                }
            }

            /// <summary>
            /// The Graphic2 item.
            /// </summary>
            [RepositoryItem("90759b2e-114b-4f84-8276-51ad2c43662b")]
            public virtual Ranorex.Picture Graphic2
            {
                get
                {
                    return _graphic2Info.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The Graphic2 item info.
            /// </summary>
            [RepositoryItemInfo("90759b2e-114b-4f84-8276-51ad2c43662b")]
            public virtual RepoItemInfo Graphic2Info
            {
                get
                {
                    return _graphic2Info;
                }
            }

            /// <summary>
            /// The Graphic3 item.
            /// </summary>
            [RepositoryItem("20a2ff18-8003-4eaa-9c1d-9694f37a0057")]
            public virtual Ranorex.Picture Graphic3
            {
                get
                {
                    return _graphic3Info.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The Graphic3 item info.
            /// </summary>
            [RepositoryItemInfo("20a2ff18-8003-4eaa-9c1d-9694f37a0057")]
            public virtual RepoItemInfo Graphic3Info
            {
                get
                {
                    return _graphic3Info;
                }
            }
        }

        /// <summary>
        /// The OEdemeTrendyolFolder folder.
        /// </summary>
        [RepositoryFolder("f060c75b-fa82-47ad-9a20-f70c90bef24e")]
        public partial class OEdemeTrendyolFolder : RepoGenBaseFolder
        {
            RepoItemInfo _noneInfo;
            RepoItemInfo _none3Info;
            RepoItemInfo _none1Info;

            /// <summary>
            /// Creates a new OEdemeTrendyol  folder.
            /// </summary>
            public OEdemeTrendyolFolder(RepoGenBaseFolder parentFolder) :
                    base("OEdemeTrendyol", "element[@automationid='481092992']/container", parentFolder, 30000, null, false, "f060c75b-fa82-47ad-9a20-f70c90bef24e", "")
            {
                _noneInfo = new RepoItemInfo(this, "None", "?/?/container/container", "", 30000, null, "d80d17d3-daa9-4ab7-add3-c38847327a7e");
                _none3Info = new RepoItemInfo(this, "None3", "?/?/container/container/container", "", 30000, null, "20b072bd-7bbc-4f84-9fe2-c90b365e6e6b");
                _none1Info = new RepoItemInfo(this, "None1", "container//link", "", 30000, null, "0dfa85af-ca92-490b-bdf0-f9a888ff6094");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f060c75b-fa82-47ad-9a20-f70c90bef24e")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f060c75b-fa82-47ad-9a20-f70c90bef24e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The None item.
            /// </summary>
            [RepositoryItem("d80d17d3-daa9-4ab7-add3-c38847327a7e")]
            public virtual Ranorex.Container None
            {
                get
                {
                    return _noneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The None item info.
            /// </summary>
            [RepositoryItemInfo("d80d17d3-daa9-4ab7-add3-c38847327a7e")]
            public virtual RepoItemInfo NoneInfo
            {
                get
                {
                    return _noneInfo;
                }
            }

            /// <summary>
            /// The None3 item.
            /// </summary>
            [RepositoryItem("20b072bd-7bbc-4f84-9fe2-c90b365e6e6b")]
            public virtual Ranorex.Container None3
            {
                get
                {
                    return _none3Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The None3 item info.
            /// </summary>
            [RepositoryItemInfo("20b072bd-7bbc-4f84-9fe2-c90b365e6e6b")]
            public virtual RepoItemInfo None3Info
            {
                get
                {
                    return _none3Info;
                }
            }

            /// <summary>
            /// The None1 item.
            /// </summary>
            [RepositoryItem("0dfa85af-ca92-490b-bdf0-f9a888ff6094")]
            public virtual Ranorex.Link None1
            {
                get
                {
                    return _none1Info.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The None1 item info.
            /// </summary>
            [RepositoryItemInfo("0dfa85af-ca92-490b-bdf0-f9a888ff6094")]
            public virtual RepoItemInfo None1Info
            {
                get
                {
                    return _none1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
