///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RonwellTask.TrendyolTestScenarios
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddProductsToCart recording.
    /// </summary>
    [TestModule("3ee3dd82-21cc-4482-88b9-a895b1bed8cd", ModuleType.Recording, 1)]
    public partial class AddProductsToCart : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RonwellTask.RonwellTaskRepository repository.
        /// </summary>
        public static global::RonwellTask.RonwellTaskRepository repo = global::RonwellTask.RonwellTaskRepository.Instance;

        static AddProductsToCart instance = new AddProductsToCart();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddProductsToCart()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddProductsToCart Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Graphic' at 54;67.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.GraphicInfo, new RecordItemIndex(0));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Graphic.Click("54;67");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SepetimTrendyolGoogleChrome.SepeteEkle' at 28;11.", repo.SepetimTrendyolGoogleChrome.SepeteEkleInfo, new RecordItemIndex(1));
            repo.SepetimTrendyolGoogleChrome.SepeteEkle.Click("28;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Back1' at 24;17.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Back1Info, new RecordItemIndex(2));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Back1.Click("24;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping5' at 170;70.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping5Info, new RecordItemIndex(3));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping5.Click("170;70");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SepetimTrendyolGoogleChrome.SepeteEkle1' at 43;9.", repo.SepetimTrendyolGoogleChrome.SepeteEkle1Info, new RecordItemIndex(4));
            repo.SepetimTrendyolGoogleChrome.SepeteEkle1.Click("43;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1503,Y=125}.", new RecordItemIndex(5));
            Mouse.MoveTo(1503, 125);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'SepetimTrendyolGoogleChrome.Graphic'.", repo.SepetimTrendyolGoogleChrome.GraphicInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.SepetimTrendyolGoogleChrome.GraphicInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'SepetimTrendyolGoogleChrome.Graphic1'.", repo.SepetimTrendyolGoogleChrome.Graphic1Info, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.SepetimTrendyolGoogleChrome.Graphic1Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1896,Y=12}.", new RecordItemIndex(8));
            Mouse.MoveTo(1896, 12);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
