///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RonwellTask.TrendyolTestScenarios
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddProductsToWishlist recording.
    /// </summary>
    [TestModule("37248c75-11ee-44e0-9ec1-7fde99441644", ModuleType.Recording, 1)]
    public partial class AddProductsToWishlist : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RonwellTask.RonwellTaskRepository repository.
        /// </summary>
        public static global::RonwellTask.RonwellTaskRepository repo = global::RonwellTask.RonwellTaskRepository.Instance;

        static AddProductsToWishlist instance = new AddProductsToWishlist();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddProductsToWishlist()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddProductsToWishlist Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping7' at 169;27.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping7Info, new RecordItemIndex(0));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping7.Click("169;27");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping8' at 168;26.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping8Info, new RecordItemIndex(1));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping8.Click("168;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping9' at 60;6.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping9Info, new RecordItemIndex(2));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping9.Click("60;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping10'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping10Info, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping10Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'FavorilerTrendyolGoogleChrome.Grouping1'.", repo.FavorilerTrendyolGoogleChrome.Grouping1Info, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.FavorilerTrendyolGoogleChrome.Grouping1Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'FavorilerTrendyolGoogleChrome.Grouping2'.", repo.FavorilerTrendyolGoogleChrome.Grouping2Info, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.FavorilerTrendyolGoogleChrome.Grouping2Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1896,Y=12}.", new RecordItemIndex(6));
            Mouse.MoveTo(1896, 12);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
