///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RonwellTask.TrendyolTestScenarios
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BlankSpacesInMandatoryFieldsValidationError recording.
    /// </summary>
    [TestModule("7230c08a-61b3-4e64-9e04-ab10e8b090f8", ModuleType.Recording, 1)]
    public partial class BlankSpacesInMandatoryFieldsValidationError : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RonwellTask.RonwellTaskRepository repository.
        /// </summary>
        public static global::RonwellTask.RonwellTaskRepository repo = global::RonwellTask.RonwellTaskRepository.Instance;

        static BlankSpacesInMandatoryFieldsValidationError instance = new BlankSpacesInMandatoryFieldsValidationError();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BlankSpacesInMandatoryFieldsValidationError()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BlankSpacesInMandatoryFieldsValidationError Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping4'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping4Info, new RecordItemIndex(0));
            Validate.Exists(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping4Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping4' at Center", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping4Info, new RecordItemIndex(1));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.Grouping4.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Üye Ol') on item 'HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOl'.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOlInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOlInfo, "Text", "Üye Ol");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOl' at Center.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOlInfo, new RecordItemIndex(3));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOl.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'HttpsWwwTrendyolComUyelikcbEqhttps.Grouping3'.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping3Info, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping3Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.ComboBox' at 88;26.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.ComboBoxInfo, new RecordItemIndex(5));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.ComboBox.Click("88;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '               ' with focus on 'HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.ComboBox'.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.ComboBoxInfo, new RecordItemIndex(6));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.ComboBox.PressKeys("               ");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.Text' at 80;26.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.TextInfo, new RecordItemIndex(7));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.Text.Click("80;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '                     ' with focus on 'HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.Text'.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.TextInfo, new RecordItemIndex(8));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.Text.PressKeys("                     ");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.UEYEOL' at 198;20.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.UEYEOLInfo, new RecordItemIndex(9));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.UEYEOL.Click("198;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'HttpsWwwTrendyolComUyelikcbEqhttps.Grouping3'.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping3Info, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping3Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.Pane' at 1891;12.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.PaneInfo, new RecordItemIndex(11));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.Pane.Click("1891;12");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
