///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RonwellTask.TrendyolTestScenarios
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BuyProductsInCart recording.
    /// </summary>
    [TestModule("6a6f39d4-a297-4582-b076-1390fa56c905", ModuleType.Recording, 1)]
    public partial class BuyProductsInCart : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RonwellTask.RonwellTaskRepository repository.
        /// </summary>
        public static global::RonwellTask.RonwellTaskRepository repo = global::RonwellTask.RonwellTaskRepository.Instance;

        static BuyProductsInCart instance = new BuyProductsInCart();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BuyProductsInCart()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BuyProductsInCart Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.LinkSepetim21' at 56;4.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.LinkSepetim21Info, new RecordItemIndex(0));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.LinkSepetim21.Click("56;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.None1' at 1397;513.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.None1Info, new RecordItemIndex(1));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.None1.Click("1397;513");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EnTrendUEruenlerTuerkiyeninOnlineAl.None2' at 128;46.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.None2Info, new RecordItemIndex(2));
            repo.EnTrendUEruenlerTuerkiyeninOnlineAl.None2.Click("128;46");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.OEdemeYap'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.OEdemeYapInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.OEdemeYapInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Ödeme Yap') on item 'EnTrendUEruenlerTuerkiyeninOnlineAl.OEdemeYap'.", repo.EnTrendUEruenlerTuerkiyeninOnlineAl.OEdemeYapInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.EnTrendUEruenlerTuerkiyeninOnlineAl.OEdemeYapInfo, "Text", "Ödeme Yap");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
