///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RonwellTask.TrendyolTestScenarios
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EmptyMandatoryFieldsValidationError recording.
    /// </summary>
    [TestModule("7320d157-d5c8-4c89-af58-cdea009605c3", ModuleType.Recording, 1)]
    public partial class EmptyMandatoryFieldsValidationError : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RonwellTask.RonwellTaskRepository repository.
        /// </summary>
        public static global::RonwellTask.RonwellTaskRepository repo = global::RonwellTask.RonwellTaskRepository.Instance;

        static EmptyMandatoryFieldsValidationError instance = new EmptyMandatoryFieldsValidationError();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EmptyMandatoryFieldsValidationError()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EmptyMandatoryFieldsValidationError Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move at {X=1277,Y=116}.", new RecordItemIndex(0));
            Mouse.MoveTo(1277, 116);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move at {X=1276,Y=219}.", new RecordItemIndex(1));
            Mouse.MoveTo(1276, 219);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click at {X=1276,Y=219}.", new RecordItemIndex(2));
            Mouse.MoveTo(1276, 219);
            Mouse.Click(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.Erkek' at 76;26.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.ErkekInfo, new RecordItemIndex(3));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.Erkek.Click("76;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.UEYEOL' at 223;23.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.UEYEOLInfo, new RecordItemIndex(4));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.UEYEOL.Click("223;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'HttpsWwwTrendyolComUyelikcbEqhttps.Grouping3'.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping3Info, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping3Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.Pane' at 1891;12.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.PaneInfo, new RecordItemIndex(6));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.Pane.Click("1891;12");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
