///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RonwellTask.TestScenarios
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CASE6 recording.
    /// </summary>
    [TestModule("e2e68f39-6739-4c55-bdbe-e36b10b168b0", ModuleType.Recording, 1)]
    public partial class CASE6 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RonwellTask.RonwellTaskRepository repository.
        /// </summary>
        public static global::RonwellTask.RonwellTaskRepository repo = global::RonwellTask.RonwellTaskRepository.Instance;

        static CASE6 instance = new CASE6();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CASE6()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CASE6 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ErkekButikleriYeniSezonUEruenler.Graphic4' at 32;32.", repo.ErkekButikleriYeniSezonUEruenler.Graphic4Info, new RecordItemIndex(0));
            repo.ErkekButikleriYeniSezonUEruenler.Graphic4.Click("32;32");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ErkekButikleriYeniSezonUEruenler.None2' at 462;225.", repo.ErkekButikleriYeniSezonUEruenler.None2Info, new RecordItemIndex(1));
            repo.ErkekButikleriYeniSezonUEruenler.None2.Click("462;225");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ErkekButikleriYeniSezonUEruenler.OEdemeTrendyol.None' at 714;258.", repo.ErkekButikleriYeniSezonUEruenler.OEdemeTrendyol.NoneInfo, new RecordItemIndex(2));
            repo.ErkekButikleriYeniSezonUEruenler.OEdemeTrendyol.None.MoveTo("714;258");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ErkekButikleriYeniSezonUEruenler.OEdemeTrendyol.None' at 820;431.", repo.ErkekButikleriYeniSezonUEruenler.OEdemeTrendyol.NoneInfo, new RecordItemIndex(3));
            repo.ErkekButikleriYeniSezonUEruenler.OEdemeTrendyol.None.MoveTo("820;431");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ErkekButikleriYeniSezonUEruenler.Back' at 15;8.", repo.ErkekButikleriYeniSezonUEruenler.BackInfo, new RecordItemIndex(4));
            repo.ErkekButikleriYeniSezonUEruenler.Back.Click("15;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ErkekButikleriYeniSezonUEruenler.EnTrendUEruenlerTuerkiyeninOnlineAl.Document' at 715;385.", repo.ErkekButikleriYeniSezonUEruenler.EnTrendUEruenlerTuerkiyeninOnlineAl.DocumentInfo, new RecordItemIndex(5));
            repo.ErkekButikleriYeniSezonUEruenler.EnTrendUEruenlerTuerkiyeninOnlineAl.Document.Click("715;385");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ErkekButikleriYeniSezonUEruenler.OEdemeTrendyol.None' at 700;282.", repo.ErkekButikleriYeniSezonUEruenler.OEdemeTrendyol.NoneInfo, new RecordItemIndex(6));
            repo.ErkekButikleriYeniSezonUEruenler.OEdemeTrendyol.None.Click("700;282");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ErkekButikleriYeniSezonUEruenler.Sepetim' at 27;9.", repo.ErkekButikleriYeniSezonUEruenler.SepetimInfo, new RecordItemIndex(7));
            repo.ErkekButikleriYeniSezonUEruenler.Sepetim.Click("27;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ErkekButikleriYeniSezonUEruenler.SepetiOnayla' at 65;16.", repo.ErkekButikleriYeniSezonUEruenler.SepetiOnaylaInfo, new RecordItemIndex(8));
            repo.ErkekButikleriYeniSezonUEruenler.SepetiOnayla.Click("65;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ErkekButikleriYeniSezonUEruenler.OEdemeTrendyol.None3' at 48;60.", repo.ErkekButikleriYeniSezonUEruenler.OEdemeTrendyol.None3Info, new RecordItemIndex(9));
            repo.ErkekButikleriYeniSezonUEruenler.OEdemeTrendyol.None3.Click("48;60");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ErkekButikleriYeniSezonUEruenler.KaydetVeDevamEt' at 141;23.", repo.ErkekButikleriYeniSezonUEruenler.KaydetVeDevamEtInfo, new RecordItemIndex(10));
            repo.ErkekButikleriYeniSezonUEruenler.KaydetVeDevamEt.Click("141;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ErkekButikleriYeniSezonUEruenler.Grouping1'.", repo.ErkekButikleriYeniSezonUEruenler.Grouping1Info, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.ErkekButikleriYeniSezonUEruenler.Grouping1Info, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Valid='True') on item 'ErkekButikleriYeniSezonUEruenler.Grouping1'.", repo.ErkekButikleriYeniSezonUEruenler.Grouping1Info, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.ErkekButikleriYeniSezonUEruenler.Grouping1Info, "Valid", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'ErkekButikleriYeniSezonUEruenler.Grouping1'.", repo.ErkekButikleriYeniSezonUEruenler.Grouping1Info, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.ErkekButikleriYeniSezonUEruenler.Grouping1Info, "Visible", "True");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
