///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RonwellTask.TestScenarios
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CASE2 recording.
    /// </summary>
    [TestModule("7b3ccaf4-7ff3-4b43-9943-e42422f1a830", ModuleType.Recording, 1)]
    public partial class CASE2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RonwellTask.RonwellTaskRepository repository.
        /// </summary>
        public static global::RonwellTask.RonwellTaskRepository repo = global::RonwellTask.RonwellTaskRepository.Instance;

        static CASE2 instance = new CASE2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CASE2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CASE2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOl'.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOlInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOlInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Üye Ol') on item 'HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOl'.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOlInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOlInfo, "Text", "Üye Ol");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOl' at 131;20.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOlInfo, new RecordItemIndex(2));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.UEyeOl.Click("131;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.Erkek' at 55;16.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.ErkekInfo, new RecordItemIndex(3));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.Erkek.Click("55;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.UEYEOL' at 202;14.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.UEYEOLInfo, new RecordItemIndex(4));
            repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.UEYEOL.Click("202;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.Grouping'.", repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.GroupingInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.HttpsWwwTrendyolComUyelikcbEqhttps.Grouping1.GroupingInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
